name: Linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.php'
  pull_request:
    branches:
      - main
    paths:
      - '**.php'

jobs:
  laravel-pint:
    name: PHP Linting (Pint)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@0.1.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
